FROM node:24.0-bullseye AS build

WORKDIR /app

COPY package*.json ./

RUN --mount=type=cache,target=/app/.npm \
    npm set cache /app/.npm && \
    npm install

COPY . .

CMD [ "npm", "run", "dev" ]